package types

import (
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core"
	"github.com/ethereum/go-ethereum/core/types"
)

// Block represents a rudimentary block structure generated by sending messages to a test chain.
type Block struct {
	// hash represents the block hash for this block.
	Hash common.Hash

	// header represents the block header for this current block.
	Header *types.Header

	// Messages represent internal EVM core.Message objects. Messages are derived from transactions after validation
	// of a transaction occurs and can be thought of as an internal EVM transaction. It contains typical transaction
	// fields plainly (e.g., no transaction signature is included, the sender is derived and simply supplied as a field
	// in a message).
	Messages []*core.Message

	// MessageResults represents the results recorded while executing transactions.
	MessageResults []*MessageResults
}

// NewBlock returns a new Block with the provided parameters.
func NewBlock(header *types.Header) *Block {
	// Create our block and return it
	block := &Block{
		Hash:           header.Hash(),
		Header:         header,
		Messages:       make([]*core.Message, 0),
		MessageResults: make([]*MessageResults, 0),
	}
	return block
}
