#!/usr/bin/env bash
set -e

echo Installing medusaget...

# Base directories
BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
MEDUSA_DIR=${MEDUSA_DIR-"$BASE_DIR/.medusa"}
MEDUSA_BIN_DIR="$MEDUSA_DIR/bin"

# URL for medusaget script
BIN_URL="https://raw.githubusercontent.com/crytic/medusa/master/medusaget/medusaget"
BIN_PATH="$MEDUSA_BIN_DIR/medusaget"

# Create directories if they don't exist
mkdir -p $MEDUSA_BIN_DIR

# Download medusaget script
curl -# -L $BIN_URL -o $BIN_PATH
chmod +x $BIN_PATH

# Detect shell and update profile
case $SHELL in
  */zsh)
    PROFILE=${ZDOTDIR-"$HOME"}/.zshenv
    PREF_SHELL=zsh
    ;;
  */bash)
    PROFILE=$HOME/.bashrc
    PREF_SHELL=bash
    ;;
  */fish)
    PROFILE=$HOME/.config/fish/config.fish
    PREF_SHELL=fish
    ;;
  *)
    echo "Medusaget: could not detect shell, manually add ${MEDUSA_BIN_DIR} to your PATH."
    exit 1
esac

# Add medusaget to PATH if not already present
if [[ ":$PATH:" != *":${MEDUSA_BIN_DIR}:"* ]]; then
    echo >> $PROFILE && echo "export PATH=\"\$PATH:$MEDUSA_BIN_DIR\"" >> $PROFILE
fi

echo "Detected your preferred shell is ${PREF_SHELL} and added medusaget to PATH."
echo "Run 'source ${PROFILE}' or start a new terminal session to use medusaget."
echo "Then, simply run 'medusaget' to start using it."
