#!/usr/bin/env bash
set -e

function install_medusaget {
  echo "Downloading medusaget..."
  curl -# -k -L "$1" -o "$2"
  chmod +x "$2"
}

function configure_shell {
  local shell_type="$1"
  local bin_path="$2"

  case "$shell_type" in
    zsh)
      echo "export PATH=\$PATH:$bin_path" >> ~/.zshrc
      ;;
    bash)
      echo "export PATH=\$PATH:$bin_path" >> ~/.bashrc
      ;;
    *)
      echo "Unknown shell. Manually add to PATH."
      exit 1
      ;;
  esac
}

function check_libusb_macos {
  if [[ ! -f /usr/local/opt/libusb/lib/libusb-1.0.0.dylib && ! -f /opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib ]]; then
    echo "Warning: libusb not found. You may need to install it manually via Homebrew (brew install libusb)."
  fi
}

function main {
  # Configurations
  base_dir=${XDG_CONFIG_HOME:-$HOME}
  root_dir="$base_dir/.medusa"
  bin_dir="$root_dir/bin"
  fetch_url="https://raw.githubusercontent.com/zachmdsi/medusa/feat/one-line-install/medusaget/medusaget"
  fetch_path="$bin_dir/medusaget"

  # Create dir & Download medusaget
  mkdir -p "$bin_dir"
  install_medusaget "$fetch_url" "$fetch_path"

  # Shell & PATH setup
  case "$SHELL" in
    *zsh)  sh_type="zsh"  ;;
    *bash) sh_type="bash" ;;
    *)     sh_type="unknown" ;;
  esac
  configure_shell "$sh_type" "$bin_dir"

  # MacOS libusb check
  [[ "$OSTYPE" =~ ^darwin ]] && check_libusb_macos

  echo "medusaget is ready. Simply run 'medusaget' to get started."
}

main "$@"

