// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package corpus

import (
	"encoding/json"
	"math/big"

	"github.com/ethereum/go-ethereum/common/hexutil"
)

var _ = (*corpusBlockHeaderMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (c CorpusBlockHeader) MarshalJSON() ([]byte, error) {
	type CorpusBlockHeader struct {
		Number    *hexutil.Big `json:"number"`
		Timestamp uint64       `json:"timestamp"`
	}
	var enc CorpusBlockHeader
	enc.Number = (*hexutil.Big)(c.Number)
	enc.Timestamp = c.Timestamp
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (c *CorpusBlockHeader) UnmarshalJSON(input []byte) error {
	type CorpusBlockHeader struct {
		Number    *hexutil.Big `json:"number"`
		Timestamp *uint64      `json:"timestamp"`
	}
	var dec CorpusBlockHeader
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Number != nil {
		c.Number = (*big.Int)(dec.Number)
	}
	if dec.Timestamp != nil {
		c.Timestamp = *dec.Timestamp
	}
	return nil
}
