[book]
authors = ["Trail of Bits"]
language = "en"
multilingual = false
src = "src"
title = "Medusa"
description = "This repository, brought to you by Trail of Bits, contains the source files for the Medusa documentation."

[output.html]
git-repository-url = "https://github.com/crytic/medusa"
edit-url-template = "https://github.com/crytic/medusa/edit/master/docs/{path}"
no-section-label = true
default-theme = "light"
