[book]
title = "medusa"
authors = ["Trail of Bits"]
language = "en"
multilingual = false
src = "src"
description = "This repository, brought to you by Trail of Bits, contains the documentation files for the medusa fuzzer."

[output.html]
git-repository-url = "https://github.com/crytic/medusa"
edit-url-template = "https://github.com/crytic/medusa/edit/master/docs/{path}"
additional-css = ["src/static/custom.css"]
default-theme = "light"

[output.html.fold]
enable = true
level = 1